### ISSUE TITLE
Check for '.only' in tests

### ISSUE THREAD

**Issue by karthikkotha** [UptakeTech/angular-testing-styleguide#27]
We should add a check if there is '.only' in the test. I've run into issues where I forgot to remove this before checking in. If '.only' is present then only that subset of the unit tests will run. Perhaps an `ESLint` check? Open to suggestions on how to handle this.

I can make this change, just looking for suggestions.

**Comment by karthikkotha** [comment]
We should add a check if there is '.only' in the test. I've run into issues where I forgot to remove this before checking in. If '.only' is present then not all the unit tests will run. Perhaps a eshint check? Open to suggestions on how to handle this.

**Comment by alexlrobertson** [comment]
This is definitely something worth looking into. I think we've all done this now and again. The ESLint rule should be pretty easy to define.

**Comment by alexlrobertson** [comment]
We should add a section about how to run only a certain suite and remind people to get rid of `.only`
