### ISSUE TITLE
`done`

### ISSUE THREAD

**Issue by alexlrobertson** [UptakeTech/angular-testing-styleguide#3]
Do we need to use Mocha’s async functionalities if ngMock solves for us so that we don't need to do async http and other operations?

```javascript
it('does something', function () {
    something
        .then(function () {
            expect(// ...);
        });

    $scope.$apply();
});
```

works identically to:

```javascript
it('does something', function (done) {
    something
        .then(function () {
            expect(// ...);
            done();
        });

    $scope.$apply();
});
```

**Comment by tykowale** [comment]
No need for done makes more sense and less code, so its a win win in my book

**Comment by alexlrobertson** [comment]
I've found that without `done`, if the promise never gets executed, the runner assumes the test passed, even though there were no expectations. I'd chalk this up to a solid +1 for using `done`.

**Comment by tykowale** [comment]
Hmm I didn't realize that, that seems like a very good reason to use `done()`. Is it possible to lint for it?

**Comment by alexlrobertson** [comment]
It would require some heavy Esprima work, which would be fun to dive into.
